services:
  frontend_girawebsite:
    build:
      context: .
    image: frontend_girawebsite:latest
    restart: unless-stopped
    networks:
      - caddy_network

networks:
  caddy_network:
    external: true